#!/usr/bin/env bash
# install and configure nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start
