#!/usr/bin/env bash
# Install and configure Nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx Full'

# Create a simple "Hello World!" index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
#

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
# Restart Nginx to apply changes
sudo service nginx restart
