#!/usr/bin/env bash
# Installs and configures nginx
apt-get update
apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "page not found" > /var/www/html/404.html

sed -i "/server_name _;/a \
	\\\n\terror_page 404 /404.html; \
    \n\n\tadd_header X-Served-By $(hostname); \
	\n\n\tlocation /redirect_me { \
	\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
	\n\t}" /etc/nginx/sites-available/default
service nginx restart
