#!/usr/bin/env bash
#ensures nginx is listening on port 80 for all IPv4
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
#sudo python3 -m http.server --directory /usr/share/nginx/html 80 > /dev/null 2>&1 &
