#!/bin/env bash
# displays clock from 0 to 12 hrs and 1 to 59 mins
hrs=0
min=1
while [ $hrs -le 12 ]; do
	echo "Hour: $hrs"
	while [ $min -le 59 ]; do
		echo $min
		(( min++ ))
	done
	(( min = 1 ))
	(( hrs++ ))
done
