#!/usr/bin/env bash
#a Bash script that uses ssh to connect to your server using
#the private key ~/.ssh/school with the user ubuntu

server="35.175.134.98"
user="ubuntu"
private_key="~/.ssh/school"

ssh -i "$private_key" "$user@$server"
